-- MySQL Script generated by MySQL Workbench
-- Tue Sep  3 00:47:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prijava
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prijava` ;

-- -----------------------------------------------------
-- Schema prijava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prijava` DEFAULT CHARACTER SET utf8 ;
USE `prijava` ;

-- -----------------------------------------------------
-- Table `prijava`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prijava`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `prijava`.`Korisnik` (
  `id_Korisnika` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `RepeatPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Korisnika`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
